services:
  - type: web
    name: barksdale-music-group
    runtime: python
    repo: https://github.com/barksdale410/barksdale-music-group
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
